config/routes.rb
=begin

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

=end

Rails.application.routes.draw do

	devise_for :users

	get 'home/index'
	get 'posts/export_posts'
	get 'posts/upvote'
	get 'posts/unvote'		
	
#	get 'posts/export_posts', defaults: { format: :csv }

	resources :posts
	resources :admin



	root 'posts#index'
#	root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/edit.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019



<% end %>



<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-6">

<h1><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> 	Edit User</h1>
<p><%= link_to 'All Users', admin_index_path %></p>

<%= form_for @user, url: admin_path(@user) do |form| %>

<div class="card">
<div class="card-body m-3">

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, :placeholder => "User's Email Address", :class => "form-control", :autofocus => true, :autocomplete => 'off' %>
  </p>
 
  <p>
    <%= form.label :encrypted_password %><br>
    <%= form.text_field :encrypted_password, :placeholder => "User's Password", :class => "form-control"  %>
  </p>

 </div>

<div class="card-footer text-muted">
<%= form.submit "Save", :class=>"btn btn-outline-secondary float-right" %>
</div>

</div>  

<% end %>


</div>

<div class="col">

</div>

</div>

<% end %>

app/views/admin/index.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-10">

<h4><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> Users</h4>

<p>
(sort by <%= link_to "Vote Count", admin_index_path(sort: "votecount"), :title=>"Sort by users who voted the most" %> OR <%= link_to "Post Count", admin_index_path(sort: "postcount"), :title=>"Sort by users who posted the most" %> OR <%= link_to "Date Created", admin_index_path(sort: "created_at"), :title=>"Sort by date user was added"  %> OR <%= link_to "A-Z", admin_index_path(sort: "az"), :title=>"Sort by user alphabetical order"  %>) | 
  <%= link_to 'All Feedback Posts', posts_path %>

  <% if user_signed_in? && ADMIN.include?(current_user.email) %>
  | <%= link_to 'New', new_admin_path, :title=>"Create new user"  %> 
  <% end %>
</p>


<table class="table table-sm table-hover all_table">
  <thead>
  <tr class="all_table_heading">
    <th>Id</th>    
    <th>User</th>    
    <th>Created At</th>
    <th>Post Count</th>
    <th>Vote Count</th>        
    <th class="text-center">
      <span class="oi oi-wrench" title="Thumbs Up" aria-hidden="true"></span> 
    </th>
  </thead>
  </tr>
 

  <tbody>
  <% @users.each do |user| %>

  <% 

  @username = user.email.split("@").first

  %>
    <tr class="">
      
      <td>
        <%= user.id %>
      </td>
      <td>
        <%= user.email %>
       </td>

      <td><div class="text-truncate" style="max-width: 100px;" ><%= user.created_at.strftime("%-m/%-d/%y") %></div></td> 

      <td>
        <%= user.postcount %>
       </td>
      <td>
        <%= user.votecount %>
       </td>      

      <td><div class="" style="max-width: 200px;">

          <% if user_signed_in? && ADMIN.include?(current_user.email) %>

          <%= link_to 'Edit', edit_admin_path(user), :title=>"Edit User" %>

          <% end %>

      </div>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

<p></p>
<%= will_paginate @users %>


</div>

<div class="col">

</div>

</div>

<% end %>

<% content_for :bottom do %>

  <%= render "posts/posttext" %>

<% end %>

app/views/admin/new.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-6">

<h1><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> New User</h1>
<p><%= link_to 'All Users', admin_index_path %></p>

<%= form_for @user, :url => {:controller => "admin", :action => "create"}, html: { method: :post } do |form| %>

<div class="card">
<div class="card-body m-3">

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email, :placeholder => "User's Email Address", :class => "form-control", :autofocus => true, :autocomplete => 'off' %>
  </p>
 
  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password, :value => 'spark1234', :placeholder => "User's Password", :class => "form-control", autocomplete: 'off'  %>
  </p>  

</div>


<div class="card-footer text-muted">
<%= form.submit "Save", :class=>"btn btn-outline-secondary float-right" %>
</div>


</div>

<% end %>

</div>

<div class="col">

</div>

</div>

<% end %>