config/routes.rb
=begin

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

=end

Rails.application.routes.draw do

	devise_for :users

	get 'home/index'
	get 'posts/export_posts'
	get 'posts/upvote'
	get 'posts/unvote'		
	
#	get 'posts/export_posts', defaults: { format: :csv }

	resources :posts
	resources :admin



	root 'posts#index'
#	root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
=begin

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

=end

class Post < ApplicationRecord

  acts_as_votable


  validates :title, length: { minimum:15, :maximum => 255 }
  validates :text, length: { minimum:10, :maximum => 65536 }
  validates :product, length: { minimum:1, :maximum => 255 }

  scope :user, -> { joins("INNER JOIN users ON posts.user_id = users.id") }


  # method to convert data to CSV delimited format
  def self.to_csv
    CSV.generate(force_quotes: true) do |csv|

      csv << ["Votes","Product","Post_Status","Created_At","Post_Title","Post_Text","Post_Resolution"]
      all.each do |postrow|

        if postrow.anonymous
          email = "Anonymous"
        else
          email = postrow.email.split("@").first
        end

        created_at = postrow.created_at.strftime('%Y-%m-%d %H:%M:%S')

        csv << [postrow.cached_votes_total, postrow.product, postrow.status, created_at, email, postrow.title, postrow.text, postrow.notes]        


        #csv << postrow.attributes.values_at(*["cached_votes_total","product","status","created_at","title","text","notes"])
      
      end
    end
  end


end

app/controllers/posts_controller.rb
=begin

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

=end

class PostsController < ApplicationController



	before_action :authenticate_user!, :except => [:show, :index, :export_posts]


	def initialize

		super


	end

	def new

	end

	def create
	  	@post = Post.new(post_params)
	  	@post.user_id = current_user.id


		  	if @post.save

		  		redirect_to :action => "index"

		  		#redirect_to @post
				#render plain: params[:post].inspect

			else
				makeflash
				render action: "new"
			end

	end

	def show
		#@post = Post.find(params[:id])	

		@posts = Post.user.where("posts.id = ?",params[:id]).select("posts.id, posts.user_id, title, text, product, status, notes, users.email, posts.created_at, posts.cached_votes_total, posts.anonymous")	
	
  		@posts.each do |post|

  			@post = post

  		end

	end


	def edit
		@post = Post.find(params[:id])
	end	


	def update

		@post = Post.find(params[:id])
	  	#@post.user_id = current_user.id

	  	#logger.info("PARAM title: " + params[:post][:title].to_s)
		#logger.info("DB title: " + @post.title)

	  	if ( PRODUCTMANAGERS.include?(current_user.email) || LEADERSHIP.include?(current_user.email) ) && (params[:post][:title] != @post.title || params[:post][:text] != @post.text || params[:post][:product] != @post.product  ) 

			flash.now[:danger] = "You only have permission to update the Status and Resolution Notes."
			render action: "edit"

			logger.info("hr, leadership and changed wrong fields")

		elsif (@post.user_id == current_user.id || ADMIN.include?(current_user.email) || (  ( PRODUCTMANAGERS.include?(current_user.email) || LEADERSHIP.include?(current_user.email) ) && ( params[:post][:notes] != @post.notes || params[:post][:status] != @post.status ) ) ) 

			logger.info("the user's post, or admin")

		  	if @post.update(post_params)

		  		redirect_to :action => "index"

		  		#redirect_to @post
				#render plain: params[:post].inspect

			else
				makeflash
				render action: "edit"
			end
		
		else

			logger.info("you don't have permissions")

			flash[:danger] = "You do not have permission to update the post."
			redirect_to :action => "index"

		end

	end


	def export_posts  

		@posts = Post.user.select("posts.id, posts.user_id, title, text, product, status, notes, users.email, posts.created_at, posts.cached_votes_total, posts.notes, posts.anonymous")

		if params[:sort] == "all"
			@posts = @posts.order("posts.status desc,posts.created_at desc")	
		elsif params[:sort] == "resolved"
			@posts = @posts.where("status = ?","Resolved").order("posts.status asc, posts.created_at desc")
		else			
			@posts = @posts.where("status = ?","Active")
			if params[:sort] == "created_at" 
				@posts = @posts.order("posts.created_at desc")
			elsif params[:sort] == "email"
				@posts = @posts.order("users.email asc")
			elsif params[:sort] == "product"
				@posts = @posts.order("posts.product asc")			
			elsif params[:sort] == "votes"
				@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")					
			else
				@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")
			end
		end

=begin 
		@posts = Post.all.user.select("posts.cached_votes_total, product, status, title, text, email, posts.created_at")

		if params[:sort] == "created_at" 
			@posts = @posts.order("posts.created_at desc")
		elsif params[:sort] == "email"
			@posts = @posts.order("users.email asc, posts.created_at desc")
		elsif params[:sort] == "product"
			@posts = @posts.order("posts.product asc, posts.created_at desc")			
		elsif params[:sort] == "votes"
			@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")										
		else
			@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")
		end
=end

		respond_to do |format|
			format.csv { send_data @posts.to_csv }
		end

	end


	def upvote

	  	@post_id = params[:id].to_s
		@post = Post.find(params[:id])
	  	@user = current_user

		if @post.upvote_from @user
			redirect_to action: "index"
		else

		end

	end

	def unvote

	  	@post_id = params[:id].to_s
		@post = Post.find(params[:id])
	  	@user = current_user

		if @post.unliked_by @user
			redirect_to action: "index"
		  
		else
		  
		end

	end

	def index

		@posts = Post.user.select("posts.id, posts.user_id, title, text, product, status, notes, users.email, posts.created_at, posts.cached_votes_total, anonymous")

		@sort = params[:sort]

		if params[:sort] == "all"
			@posts = @posts.order("posts.status desc,posts.created_at desc")
			@sortname = "(all statuses)"	
		elsif params[:sort] == "resolved"
			@posts = @posts.where("status = ?","Resolved").order("posts.status asc, posts.created_at desc")
			@sortname = "(resolved status)"
		else			
			@posts = @posts.where("status = ?","Active")
			if params[:sort] == "created_at" 
				@posts = @posts.order("posts.created_at desc")
				@sortname = "(sorted by most recent)"
			elsif params[:sort] == "email"
				@posts = @posts.order("users.email asc")
				@sortname = "(sorted by user)"
			elsif params[:sort] == "product"
				@posts = @posts.order("posts.product asc")	
				@sortname = "(sorted by product)"		
			elsif params[:sort] == "votes"
				@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")
				@sortname = "(sorted by most votes)"						
			else
				@posts = @posts.order("posts.created_at desc")
				#@posts = @posts.order("posts.cached_votes_total desc, posts.created_at desc")
				@sort = "votes"
				@sortname = "(sorted by most recent)"
			end
		end

		@posts = @posts.paginate(:page => params[:page], :per_page => 50) 


	end




private

	def post_params
		params.require(:post).permit(:title, :text, :product, :status, :notes, :anonymous)
	end

	def makeflash
		#flash.now[:danger] = @bookmark.errors.full_messages
		flash.now[:danger] = @post.errors.full_messages
	end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posttext.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-post-title font-weight-bold" id="post-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-post-body mx-3 my-3">

        <p><span class="font-weight-bold">Text:</span> <span id="post-text"></span></p>
        <p><span class="font-weight-bold">Resolution:</span> <span id="post-notes"></span></p> 
        <p><span class="font-weight-bold">Submitter:</span> <span id="post-author"></span></p>        
        <p><span class="font-weight-bold">Product:</span> <span id="post-product"></span></p>
        <p><span class="font-weight-bold">Votes:</span> <span id="post-votes"></span></p> 
        <p><span class="font-weight-bold">Created:</span> <span id="post-created"></span></p>        
        <p><span class="font-weight-bold">Status:</span> <span id="post-status"></span></p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-6">

<h1><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> Edit Post Detail</h1>


<%= form_with model: @post, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, :placeholder => "Title of Post", :class => "form-control" %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, :placeholder => "More info about Post", :class => "form-control", :rows => 4  %>
  </p>

  <p>
    <%= form.label :product %><br>

    <% if false %>

    <%= form.text_field :product, :placeholder => "Product Area", :class => "typeahead form-control", autocomplete: 'off' %>

    <%= form.select :product, options_for_select([["Darwin","Darwin"],["DeepNLP","DeepNLP"],["SparkPredict","SparkPredict"],["DeepArmor","DeepArmor"]], :selected => [:product, :product]), {}, {:class => "form-control"} %>

    <%= form.select :product, options_for_select(["Darwin","DeepNLP","SparkPredict","DeepArmor"], :selected=>:product), {}, {:class => "form-control"} %>    

    <% end %>

    <%= form.select :product, PRODUCTS, {}, {:class => "form-control"} %>
  </p>   
 
  <p>
    <%= form.label :anonymous %><br>
    <%= form.check_box :anonymous, {:class => "checkbox form-control"} %>
  </p>

 <p>
    <%= form.select :status, STATUS, {}, {:class => "form-control"} %>
  </p>   

  <p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes, :placeholder => "Human Resources can add comments here.", :class => "form-control", :rows => 4  %>
  </p>

  <p>
    <%= form.submit "Save", :class=>"btn btn-outline-secondary " %>
  </p>
<% end %>

<p><%= link_to 'Return to Home', posts_path %></p>

</div>

<div class="col">

</div>

</div>

<% end %>

app/views/posts/index.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-11">

<h4><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%>Company Feedback</h4>
<p><strong>Important:</strong>  Keep posts professional, positive, and specific. ✌️</p>
<p><span class="text-danger font-weight-bold">*</span> means HR or an administrator has commented. Click post to review.</p>
<p>( filter/sort by 

<%= link_to "Most Votes", posts_path(sort: "votes"), :title=>"Sort by most Upvotes" %>,

<%= link_to "Most Recent", posts_path(sort: "created_at"), :title=>"Sort by the latest feedback added"  %>,

<%= link_to "All Statuses", posts_path(sort: "all"), :title=>"No Filter - All Posts" %>,

<%= link_to "Resolved", posts_path(sort: "resolved"), :title=>"Filter by Resolved Posts" %>,

<%= link_to "Category", posts_path(sort: "product"), :title=>"Sort by category" %>

)

<% if false %>
   OR <%= link_to "User", posts_path(sort: "email"), :title=>"Sort by user creating the feedback (A-Z)"  %>) 
<% end %>

  | 
<%= link_to 'New', new_post_path, :title=>"Create new feedback"  %>
   | 
  <%= link_to "Download", posts_export_posts_path(sort: @sort, format: "csv"), :title=>"Download all feedback as a csv file to import into Excel"  %> |
  <%= link_to "About", home_index_path, :title=>"About the Ranker tool"  %> |
      <% if user_signed_in? %>
<%= link_to 'Logout (' + current_user.email.split("@").first.to_s + ')', destroy_user_session_path, method: :delete, :title=>"Logout of the Ranker"  %>
      <% else %>
<%= link_to 'Login to Post', new_user_session_path, :title=>"Login into the Ranker to add feedback and upvote feedback"  %>
      <% end %>
<% if user_signed_in? && ADMIN.include?(current_user.email) %>
 | <%= link_to 'Admin', admin_index_path, :title=>"Create and edit users"  %>
<% end %>

<small><%= @sortname %></small> 

</p>


<table class="table table-sm table-hover all_table">
  <thead>
  <tr class="all_table_heading">
    <th style="max-width: 20px;">Rank</th>    
    <th></th>
    <th>Category</th>    
    <th>Title <span class="font-weight-normal small">(click cell or Show link to the right for detail)</span></th>
    <th class="d-none">Text <span class="font-weight-normal small">(click text cell for detail)</span></th>
    <th class="d-none">Resolution</th>     
    <th class="d-none">Submitter</th>    
    <th>Created</th>  
    <th>Status</th>       
    <th class="text-center">
      <span class="oi oi-wrench" title="Thumbs Up" aria-hidden="true"></span> 
    </th>
  </thead>
  </tr>
 

  <tbody>
  <% @posts.each do |post| %>

  <% 

  @username = post.email.split("@").first

  %>
    <tr class="">
      
      <td><div data-votes="<%= post.get_upvotes.size %>" title="The number of upvotes by users.">
        <%= post.get_upvotes.size %>
      </td>
      <td class="voter">

<% if user_signed_in? %>

<% if current_user.voted_for? post %>

<%= link_to "<span class=\"oi oi-action-undo\" aria-hidden=\"true\"></span>".html_safe, posts_unvote_path(:id=>post.id), :title=>"Cancel your vote for this post"%>

<% else %>

<%= link_to "<span class=\"oi oi-thumb-up\" aria-hidden=\"true\"></span>".html_safe, posts_upvote_path(:id=>post.id), :title=>"Upvote this post" %>

<% end %>

<% end %>

       </td>


      <td id="pproduct"><div data-title="<%= post.product %>" title="<%= post.product %>"><%= post.product %></div></td>
      <td id="ptitle"><div class="text-truncate" style="max-width: 600px;" data-title="<%= post.title %>" title="<%= post.title %>"><%= post.title %> 

<% if !post.notes.blank? %>
  <span class="text-danger font-weight-bold">*</span>
<% end %>


</div></td>
      <td class="d-none"><div data-text="<%= post.text %>" title="<%= post.text %>"><%= post.text %></div></td>
      <td class="d-none"><div data-notes="<%= post.notes %>" title="<%= post.notes %>"><%= post.notes %></div></td>      
      <td class="d-none"><div>

<% if post.anonymous %>

Anonymous

<% else %>

<%= @username %>

<% end %>        

</div></td>

<% if false %>

      <td><div><%= post.created_at.strftime("%-m/%-d/%y") %></div></td>

<% end %>

      <td><div>
        <%= time_ago_in_words(post.created_at) %>
        </div></td>
      <td><div><%= post.status %></div></td>            
      <td><div>
      
        <%= link_to 'Show', post_path(post), :title=>"Click to view post details including title, text, product and resolution by product manager. Post Id is " + post.id.to_s %>
      
        <% if user_signed_in? && ( post.user_id == current_user.id || ADMIN.include?(current_user.email) || PRODUCTMANAGERS.include?(current_user.email) ) %>
        | 
          <%= link_to 'Edit', edit_post_path(post), :title=>"Click to edit post and resolution by product manager. Post Id is " + post.id.to_s %>
        <% end %>    
      </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<p></p>
<%= will_paginate @posts %>


</div>

<div class="col">

</div>

</div>

<% end %>

<% content_for :bottom do %>

  <%= render "posts/posttext" %>

<% end %>

app/views/posts/new.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-6">

<h1><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> New Post</h1>

<%= form_with scope: :post, url: posts_path, local: true do |form| %>

<div class="card">
<div class="card-body m-3">

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, :placeholder => "Title of Post", :class => "form-control", :autofocus => true %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, :placeholder => "More info about Post", :class => "form-control", :rows => 4  %>
  </p>

  <p>
    <%= form.label :product %><br>
    <%= form.select :product, PRODUCTS, {}, {:class => "form-control"} %>

  </p>  

  <p>
    <%= form.label :anonymous %><br>
    <%= form.check_box :anonymous, {:checked=>false, :class => "checkbox form-control"} %>

  </p>

</div>


<div class="card-footer text-muted">
<%= link_to 'Return to Home', posts_path, :class => "align-middle" %>
<%= form.submit "Save", :class=>"btn btn-outline-secondary float-right" %>
</div>


</div>

<% end %>

</div>

<div class="col">

</div>

</div>

<% end %>

app/views/posts/show.html.erb
<% if false %>

Copyright (C) Mark Milligan - All Rights Reserved
Unauthorized copying of this file, via any medium is strictly prohibited
Proprietary and confidential
Written by Mark Milligan <markmilligan@me.com>, 2019

<% end %>

<% content_for :content do %>

<div class="row"> 

<div class="col">

</div>

<div class="col-12 col-md-6">

<h1><%= link_to "<span class=\"oi oi-home\" aria-hidden=\"true\"></span>".html_safe, posts_path, :title=>"Show most voted posts"%> Post Detail</h1>

<div class="card">
<div class="card-body m-3">

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<p>
  <strong>Resolution Notes:</strong>
  <%= @post.notes %>
</p>

<p>
  <strong>Submitter:</strong>

<% if @post.anonymous %>

  Anonymous

<% else %>

  <%= @post.email.split("@").first %>

<% end %>

</p>

<p>
  <strong>Product:</strong>
  <%= @post.product %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @post.cached_votes_total %>
</p>

<p>
  <strong>Created:</strong>
  <%= time_ago_in_words(@post.created_at) %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.status %>
</p>

</div>

<div class="card-footer text-muted">
<%= link_to "Return to Home", posts_path, :title=>"Show most voted posts"%>
</div>

</div>

</div>

<div class="col">

</div>

</div>

<% end %>